@extends('Viewers.master_viewers')

@section('css')
    @endsection

@section('konten')
<div class="container page-anim">
    <div class="main-grid">

        <div class="main-content">

            <div class="ph-breadcrumb">
                <a href="/">Home</a> / <a href="/kategori/politik">Politik</a> / <span style="color:var(--text);">RUU Pemilu Resmi Disahkan DPR...</span>
            </div>

            <div class="article-cat">Nasional · Politik</div>
            <h1 class="article-title">RUU Pemilu Resmi Disahkan DPR dalam Rapat Paripurna Hari Ini</h1>

            <div class="article-byline">
                <div class="a-avatar">BS</div>
                <div>
                    <div class="a-author">Budi Santoso</div>
                    <div class="a-date">10 Maret 2026 · 14:30 WIB</div>
                </div>
                <div class="a-stats">
                    <div class="a-stat">👁️ 12.5K Kali Dibaca</div>
                    <div class="a-stat">💬 45 Komentar</div>
                </div>
            </div>

            <div class="article-hero">
                🏛️
            </div>

            <div class="article-body">
                <p><strong>JAKARTA, FNM</strong> — Dewan Perwakilan Rakyat (DPR) secara resmi telah mengesahkan Rancangan Undang-Undang (RUU) Pemilihan Umum menjadi Undang-Undang dalam Rapat Paripurna yang digelar pada Selasa siang.</p>

                <p>Pengesahan ini diwarnai dengan berbagai interupsi dari sejumlah fraksi, namun pada akhirnya mayoritas anggota dewan menyetujui draf final yang diajukan oleh Panitia Kerja (Panja).</p>

                <blockquote>
                    "Pengesahan RUU Pemilu ini adalah langkah maju bagi demokrasi kita. Terdapat beberapa penyesuaian terkait ambang batas parlemen dan sistem kampanye digital," ujar Ketua Panja RUU Pemilu.
                </blockquote>

                <h2>Poin-Poin Penting Perubahan</h2>
                <p>Salah satu perubahan paling signifikan dalam aturan baru ini adalah pemotongan masa kampanye dari yang sebelumnya 6 bulan menjadi hanya 75 hari. Hal ini bertujuan untuk menekan biaya politik serta mengurangi potensi polarisasi yang berkepanjangan di masyarakat.</p>

                <p>Selain itu, aturan mengenai penggunaan kecerdasan buatan (AI) dalam materi kampanye juga diatur secara ketat. Peserta pemilu diwajibkan menyertakan label 'Generated by AI' pada setiap konten visual maupun audio yang dibuat menggunakan teknologi tersebut.</p>

                <p>Meski telah disahkan, sejumlah lembaga swadaya masyarakat (LSM) yang berfokus pada pemilu menyatakan akan mengajukan *judicial review* ke Mahkamah Konstitusi terkait pasal pembatasan kampanye independen.</p>
            </div>

            <div class="reaction-bar">
                <div class="rb-label">Bagaimana tanggapan Anda?</div>
                <button class="reaction-btn active">
                    👍 <span class="rb-count">1.2K</span>
                </button>
                <button class="reaction-btn">
                    ❤️ <span class="rb-count">850</span>
                </button>
                <button class="reaction-btn">
                    🤯 <span class="rb-count">320</span>
                </button>
                <button class="reaction-btn">
                    😢 <span class="rb-count">45</span>
                </button>
                <button class="reaction-btn">
                    😡 <span class="rb-count">112</span>
                </button>
            </div>

            <div class="share-bar">
                <div class="share-label">Bagikan artikel ini:</div>
                <button class="share-btn sb-fb">Facebook</button>
                <button class="share-btn sb-tw">Twitter / X</button>
                <button class="share-btn sb-wa">WhatsApp</button>
                <button class="share-btn sb-copy" onclick="showToast('Link berhasil disalin!')">🔗 Salin Link</button>
            </div>

            <div class="comments-section">
                <div class="cs-title">Komentar Pembaca (45)</div>

                <div class="comment-form">
                    <textarea class="cf-input" placeholder="Tulis komentar Anda di sini... Minta tolong gunakan bahasa yang sopan ya cuy!"></textarea>
                    <div class="cf-foot">
                        <input type="text" class="cf-name" placeholder="Nama Anda (Opsional)">
                        <button class="cf-submit" onclick="showToast('Komentar berhasil dikirim dan menunggu moderasi')">Kirim Komentar</button>
                    </div>
                </div>

                <div class="comment-list">
                    <div class="comment-item">
                        <div class="ci-avatar">A</div>
                        <div class="ci-body">
                            <div class="ci-user">Agus Pratama</div>
                            <div class="ci-time">2 Jam lalu</div>
                            <div class="ci-text">Wah, masa kampanye diperpendek jadi 75 hari doang? Bagus sih biar masyarakat nggak terlalu lama panas-panasan. Semoga beneran efektif!</div>
                            <div class="ci-acts">
                                <span class="ci-act">👍 Suka (12)</span>
                                <span class="ci-act">Balas</span>
                            </div>
                        </div>
                    </div>

                    <div class="comment-item">
                        <div class="ci-avatar">R</div>
                        <div class="ci-body">
                            <div class="ci-user">Rina_88</div>
                            <div class="ci-time">5 Jam lalu</div>
                            <div class="ci-text">Aturan soal AI itu yang paling penting sekarang. Takutnya banyak *deepfake* pas musim pemilu nanti.</div>
                            <div class="ci-acts">
                                <span class="ci-act">👍 Suka (34)</span>
                                <span class="ci-act">Balas</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div style="text-align: center; margin-top: 20px;">
                    <button class="btn btn-outline">Muat Komentar Lainnya ➔</button>
                </div>
            </div>

        </div> <div class="sidebar-col">
            @include('Viewers.layout.sidebar')
        </div>

    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function() {
        console.log("Halaman Detail Artikel berhasil di-load!");
    });
</script>
@endsection
